version: "3"
tasks:
  migrate:
    desc: applying migrations
    cmds:
      - go run ./cmd/migrator --migrations-path={{.MIGRATIONS_PATH}} --migrations-table={{.MIGRATIONS_TABLE}} --db-url={{.DB_URL}}
    vars:
      MIGRATIONS_PATH: "./migrations"
      MIGRATIONS_TABLE: "migrations"
      DB_URL: "postgres:postgres@localhost:5432/employees"
